language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t psivori/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true psivori/docker-react npm run test